name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # - name: Set PYTHONPATH
    #   run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV

    # - name: Print PYTHONPATH
    #   run: echo $PYTHONPATH

    # - name: List directory structure
    #   run: ls -R

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with pytest and generate coverage report
      run: |
        xvfb-run pytest --cov=src --cov-report=xml --cov-report=term
        
    # Store coverage reports as artifacts
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
          name: coverage-report
          path: |
            .coverage
            htmlcov/
      
